### PR TITLE
Fixed some URLs and changed some to HTTPS

### PR DESCRIPTION
**Pull request by einsteinsfool**
I ran `grep -rnw . -e 'http:'` in the repo directory and fixed outdated URLs and changed some from `http://` to `https://`.

Out of 6848 results, 6277 (which is ~92%) were to old Qt documentation at `qt.nokia.com`. Changed them to the new domain `doc.qt.io` which has archived the old docs.

One URL (in 2 occurrences) was outdated and I couldn't find a new version of the page so I linked instead to an Internet Archive version.
This URL: `http://qt.nokia.com/products/appdev/add-on-products/catalog/4/Utilities/qtbrowserplugin` became this one: `https://web.archive.org/web/20090902141130/qt.nokia.com/products/appdev/add-on-products/catalog/4/Utilities/qtbrowserplugin/`.

This URL on the other hand was also outdated:
`http://devedge-temp.mozilla.org/library/manuals/2002/plugin/1.0/`
...so I checked it in Internet Archive, then googled and got a live version:
`https://developer.mozilla.org/en-US/docs/Plugins/Guide`

Clearly checking all 494 files would be cumbersome so this is the script I ran:
`find ./ -type f -exec sed -i -E 's/http:\/\/qt.nokia.com\/doc\/4.6\/([-a-z0-9])+.html/https:\/\/doc.qt.io\/archives\/4.6\/\1.html/g' {} \;`
It reduces the number of `http:` occurrences from 6848 to 795.
You can additionally run:
```
find ./ -type f -exec sed -i 's/http:\/\/qt.nokia.com\/doc\/trademarks.html/https:\/\/doc.qt.io\/archives\/4.6\/trademarks.html/g' {} \;
find ./ -type f -exec sed -i 's/http:\/\/www.w3.org/https:\/\/www.w3.org/g' {} \;
find ./ -type f -exec sed -i 's/http:\/\/www.qt-project.org\/legal/https:\/\/www1.qt.io\/terms-conditions/g' {} \;
```
...and get the number down to 80 (checked with `grep -r 'http:' | wc -l`) in 28 files (checked with `grep -rl 'http:' | wc -l`).

### CODE REVIEW

**Comment by ossilator** [comment]
https://wiki.qt.io/Qt_Contribution_Guidelines

**Comment by Skycoder42** [comment]
@ossilator If you don't want PRs/Issues here, you can disable them in the repository settings.

**Comment by ossilator** [comment]
have you actually _tried_ that? ;)

**Comment by Skycoder42** [comment]
I remember doing it... but check now I can't find a way to disable PRs - apparently I confused it with archiving the repository, because that does disable PRs - my bad...

**Pull request closed without merging**
